# Generated by Django 2.1 on 2019-07-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_pulse', '0005_add_agency_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='hsts_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
