# Generated by Django 2.2.4 on 2019-10-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_pulse', '0006_entry_hsts_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agency',
            name='description',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='agency',
            name='facebook',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='agency',
            name='phone_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='agency',
            name='twitter',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='agency',
            name='website',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
