# Generated by Django 2.1 on 2019-12-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civic_pulse", "0006_entry_hsts_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="notes",
            field=models.CharField(blank=True, max_length=500),
        )
    ]
