# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-06 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
